name: Release
permissions:
  contents: write
  id-token: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./zebrash/go.mod
          cache: true

      # Build Go -> WASM in zebrash/
      - name: Build WebAssembly (Go)
        working-directory: zebrash
        run: |
          export GOOS=js
          export GOARCH=wasm
          go build -o main.wasm .

      # Wasm_exec.js is currently bundled. Later we will use the copied handler
      # - name: Copy wasm_exec.js next to the wasm
      #   run: |
      #    cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" zebrash/wasm_exec.js#

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org

      - name: Install
        run: npm ci

      - name: Ensure package.json matches tag
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$TAG" != "$PKG_VERSION" ]; then
            echo "Tag v$TAG does not match package.json version $PKG_VERSION"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      - name: Compute release title
        id: meta
        run: |
          RELEASE_VERSION="${GITHUB_REF_NAME#v}"
          ZEBRASH_VERSION=$(awk '/^module[[:space:]]+/ {print $2; exit}' zebrash/go.mod)

          # Export para pasos siguientes
          echo "release_version=$RELEASE_VERSION" >> "$GITHUB_OUTPUT"
          echo "zebrash_version=$ZEBRASH_VERSION" >> "$GITHUB_OUTPUT"
          echo "release_title=${RELEASE_VERSION} | Z: ${ZEBRASH_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release (auto notes, no artifacts)
        run: |
          gh release create "${GITHUB_REF_NAME}" \
            --verify-tag \
            --generate-notes \
            --title "${{ steps.meta.outputs.release_title }}"

      - name: Publish to NPM
        run: npm publish
